### ISSUE TITLE
API Tisséo -> Implémentation JOURNEY

### ISSUE THREAD

**Issue by docjyJ** [Mobilite-des-personnes-TSA/map-app#1]
Renvoie un trajet compatible OpenData
Args : 

- Adresse/Lieu de départ (Adresse ou GPS)
- Adresse/Lieu d'arrivée (Adresse ou GPS)
- Date de départ
- Date d'arrivée
- Modes transport pris en compte

**Comment by BoireauJInsa** [comment]
Renvoie un trajet compatible OpenData
Args : 

- Adresse/Lieu de départ (Adresse ou GPS)
- Adresse/Lieu d'arrivée (Adresse ou GPS)
- Date de départ
- Date d'arrivée
- Modes transport pris en compte

**Comment by docjyJ** [comment]
Implémenté dans la branche de tibo
